variables:
  IMAGE_API_NAME: anassdahchour/api-server
  IMAGE_FRONT_NAME: anassdahchour/react-app
stages:
  - build
  - test
  - deploy

build-image:
  image: docker
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:dind


  before_script:
    - docker info
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - echo $DOCKER_HOST

  tags:
    - docker
  script:
    - docker build -t $IMAGE_API_NAME .
    - cd client
    - docker build -t $IMAGE_FRONT_NAME .
    - docker push $IMAGE_API_NAME
    - docker push $IMAGE_FRONT_NAME





test-job1:
  stage: test
  image: node:lts-alpine
  script:
    - cd client
    - yarn install
    - yarn test
  tags:
    - docker



deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  tags:
    - docker
