variables:
  IMAGE_API_NAME: anassdahchour/api-server
  IMAGE_FRONT_NAME: anassdahchour/react-app
stages:
  - deploy
  - build
  - test
  - package
build:
  stage: build
  image: node:lts-alpine
  script:
    - yarn install --frozen-lockfile
    - cd client
    - yarn install --frozen-lockfile
    - cd ..
  artifacts:
    paths:
      - node_modules/
      - client/node_modules/
      - server.ts
  tags:
    - docker
  
build-image:
  stage: package
  image: docker
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:dind


  before_script:
    - docker info
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - echo $DOCKER_HOST

  tags:
    - docker
  script:
    - docker build -t $IMAGE_API_NAME .
    - cd client
    - docker build -t $IMAGE_FRONT_NAME .
    - docker push $IMAGE_API_NAME
    - docker push $IMAGE_FRONT_NAME





run_tests:
  stage: test
  image: node:lts-alpine
  script:
    - cd client
    - yarn install
    - yarn test
  tags:
    - docker



deploy-prod:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY anassdah5@34.155.100.38 "
        docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" &&
        docker-compose -f docker-compose.yml up -d"

  tags:
    - docker
