variables:
  IMAGE_NAME: anassdahchour/api-server

stages:
  - test
  - build
  - deploy

build-image:
  image: docker:20.10.16
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:20.10.16-dind


  before_script:
    - docker info
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - echo $DOCKER_HOST

  tags:
    - docker


  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME






test-job1:
  stage: test
  image: node:lts-alpine
  script:
    - cd client
    - yarn install
    - yarn test
  tags:
    - docker



deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  tags:
    - docker
