apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: api-server
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/mern-app: "true"
        io.kompose.service: api-server
    spec:
      containers:
        - env:
            - name: DB-URL
              value: mongodb://mongo/myFirstDatabase.items
          image: anassdahchour/api-server
          imagePullPolicy: IfNotPresent
          name: api-server
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
