# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: node:lts-alpine

steps:

- script: |
    - yarn install --frozen-lockfile
    - cd client
    - yarn install --frozen-lockfile

  displayName: 'yarn install and build'
