version: "3.8"
services:
  api-server:
    image: anassdahchour/api-server
    ports:
      - "4000:4000"
    environment:
      - DB-URL=mongodb://mongo/myFirstDatabase.items
    networks:
      - mern-app
    depends_on:
      - mongo
  react-app:
    image: anassdahchour/react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - api-server
  mongo:
    image: mongo:4.2.20-rc0-bionic
    ports:
    - "27017:27017"
networks:
  mern-app:
    driver: bridge